# Q2. Row Echelon Form:
Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations

import numpy as np

In [1]:
import numpy as np

np.random.seed(11)
A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)


Matrix A:
[[9 0 1 7 1]
 [7 2 8 0 0]
 [4 2 1 5 5]
 [7 4 1 8 8]
 [1 3 6 2 2]]


In [2]:
def row_echelon_form(matrix):
    m = len(matrix)
    n = len(matrix[0])
    lead = 0

    for r in range(m):
        if lead >= n:
            return matrix
        i = r
        while matrix[i][lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return matrix
        matrix[i], matrix[r] = matrix[r], matrix[i]

        lv = matrix[r][lead]
        matrix[r] = [mrx / float(lv) for mrx in matrix[r]]

        for i in range(m):
            if i != r:
                lv = matrix[i][lead]
                matrix[i] = [iv - lv*rv for rv, iv in zip(matrix[r], matrix[i])]
        lead += 1

    return matrix

A_reduced = row_echelon_form(A)
print("\nRow Echelon Form of Matrix A:")
print(np.array(A_reduced))



Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 1]
 [0 0 0 0 0]]
